name: Publish to Github releases

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix permissions
        run: chmod +x gradlew

      - name: Build project
        run: |
          ./gradlew jar packageWinX64 packageLinuxX64
          mv headless/build/libs/gdx*.jar headless/build/libs/gdx-TiledTsxBorderCreator-headless.jar
          mv lwjgl3/build/libs/gdx*.jar lwjgl3/build/libs/gdx-TiledTsxBorderCreator-desktop.jar

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lwjgl3/build/libs/gdx-TiledTsxBorderCreator-desktop.jar
            headless/build/libs/gdx-TiledTsxBorderCreator-headless.jar
            lwjgl3/build/construo/dist/gdx-TiledTsxBorderCreator-linuxX64.zip
            lwjgl3/build/construo/dist/gdx-TiledTsxBorderCreator-winX64.zip
